"use client";
import { FormEvent, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";

type FormState = { propertyType: string; area: string; ceiling: string; hvac: string; zones: string; model: string; scentFamily: string; city: string; name: string; phone: string; email: string; notes: string };
const initial: FormState = { propertyType: "", area: "", ceiling: "", hvac: "", zones: "", model: "", scentFamily: "", city: "", name: "", phone: "", email: "", notes: "" };
const propertyTypes = ["Luxury home", "Hotel", "Corporate office", "Retail / showroom", "Restaurant / club", "Spa / salon", "Real estate", "Event venue", "Other"];
const field = "w-full rounded-none border border-black/20 bg-transparent px-4 py-3.5 text-sm outline-none focus:border-black";

export default function SpaceSelector() {
  const [step, setStep] = useState(0); const [form, setForm] = useState(initial); const [status, setStatus] = useState<"idle"|"sending"|"sent"|"error">("idle");
  const set = (key: keyof FormState, value: string) => setForm(prev => ({ ...prev, [key]: value }));
  const result = useMemo(() => {
    const area = Number(form.area || 0); const isSmall = area > 0 && area <= 250; const open = ["Luxury home", "Hotel", "Corporate office", "Retail / showroom", "Restaurant / club", "Real estate", "Event venue"].includes(form.propertyType);
    if (isSmall && !open) return { title: "Statement reed or compact system", detail: "A passive reed may suit this intimate room; choose a compact machine if you need scheduling or stronger control." };
    if (area > 3000 || form.hvac === "Central HVAC") return { title: "Commercial or HVAC assessment", detail: "The property is likely to need one or more commercial systems. Final selection depends on air handling and zone layout." };
    return { title: "Compact programmable system", detail: "A waterless system is the likely starting point. HUME will confirm output, placement and oil consumption after reviewing airflow." };
  }, [form]);
  const canContinue = step === 0 ? !!form.propertyType : step === 1 ? !!form.area && !!form.ceiling && !!form.hvac : true;
  async function submit(e: FormEvent) { e.preventDefault(); setStatus("sending"); try { const r = await fetch("/api/spaces-consultation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!r.ok) throw new Error(); setStatus("sent"); } catch { setStatus("error"); } }
  if (status === "sent") return <div className="py-16 text-center"><CheckCircle2 className="mx-auto" size={38}/><h2 className="mt-6 font-serif text-4xl">Your space is on our desk.</h2><p className="mx-auto mt-4 max-w-lg text-sm leading-7 text-black/60">HUME Spaces has received your brief. We’ll review the property details and contact you with the next step.</p></div>;
  return <form onSubmit={submit} className="min-h-[560px]">
    <div className="mb-12 flex gap-2">{[0,1,2,3].map(i => <span key={i} className={`h-1 flex-1 ${i <= step ? "bg-[#19231e]" : "bg-black/10"}`}/>)}</div>
    {step === 0 && <div><p className="text-[10px] uppercase tracking-[.3em] text-black/45">01 · Property</p><h2 className="mt-5 font-serif text-4xl">What are we scenting?</h2><div className="mt-8 grid gap-3 sm:grid-cols-2">{propertyTypes.map(x => <button type="button" key={x} onClick={() => set("propertyType", x)} className={`border p-4 text-left text-sm ${form.propertyType === x ? "border-[#19231e] bg-[#19231e] text-white" : "border-black/15 hover:border-black/50"}`}>{x}</button>)}</div></div>}
    {step === 1 && <div><p className="text-[10px] uppercase tracking-[.3em] text-black/45">02 · Volume & airflow</p><h2 className="mt-5 font-serif text-4xl">Tell us about the air.</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="text-xs">Approximate area (sq ft)<input type="number" min="20" value={form.area} onChange={e=>set("area",e.target.value)} className={`${field} mt-2`}/></label><label className="text-xs">Ceiling height<select value={form.ceiling} onChange={e=>set("ceiling",e.target.value)} className={`${field} mt-2`}><option value="">Select</option><option>Under 10 ft</option><option>10–15 ft</option><option>Over 15 ft / double height</option><option>Not sure</option></select></label><label className="text-xs">Air conditioning<select value={form.hvac} onChange={e=>set("hvac",e.target.value)} className={`${field} mt-2`}><option value="">Select</option><option>Split / standalone AC</option><option>Central HVAC</option><option>No AC / open-air</option><option>Not sure</option></select></label><label className="text-xs">Number of scent zones<input value={form.zones} onChange={e=>set("zones",e.target.value)} className={`${field} mt-2`} placeholder="e.g. lobby + corridor"/></label></div></div>}
    {step === 2 && <div><p className="text-[10px] uppercase tracking-[.3em] text-black/45">03 · Recommendation</p><h2 className="mt-5 font-serif text-4xl">{result.title}</h2><p className="mt-5 max-w-xl text-sm leading-7 text-black/60">{result.detail}</p><div className="mt-9 grid gap-5 sm:grid-cols-2"><label className="text-xs">Preferred arrangement<select value={form.model} onChange={e=>set("model",e.target.value)} className={`${field} mt-2`}><option value="">Let HUME recommend</option><option>Purchase equipment</option><option>Managed monthly service</option><option>Signature scent programme</option></select></label><label className="text-xs">Preferred scent family<select value={form.scentFamily} onChange={e=>set("scentFamily",e.target.value)} className={`${field} mt-2`}><option value="">Open to recommendation</option><option>Fresh / mineral</option><option>White tea / citrus</option><option>Green / botanical</option><option>Woody / amber</option><option>Floral / oud</option></select></label><label className="text-xs sm:col-span-2">City<input value={form.city} onChange={e=>set("city",e.target.value)} className={`${field} mt-2`} placeholder="Project location"/></label></div><p className="mt-6 text-xs leading-5 text-black/45">This is a preliminary recommendation, not a coverage guarantee. Final equipment is selected after reviewing ceiling height, airflow and placement.</p></div>}
    {step === 3 && <div><p className="text-[10px] uppercase tracking-[.3em] text-black/45">04 · Consultation</p><h2 className="mt-5 font-serif text-4xl">Where should we send the plan?</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="text-xs">Name<input required value={form.name} onChange={e=>set("name",e.target.value)} className={`${field} mt-2`}/></label><label className="text-xs">Phone / WhatsApp<input required value={form.phone} onChange={e=>set("phone",e.target.value)} className={`${field} mt-2`}/></label><label className="text-xs">Email<input required type="email" value={form.email} onChange={e=>set("email",e.target.value)} className={`${field} mt-2`}/></label><label className="text-xs">Anything else?<input value={form.notes} onChange={e=>set("notes",e.target.value)} className={`${field} mt-2`}/></label></div>{status === "error" && <p className="mt-5 text-sm text-red-700">We couldn’t submit this brief. Please try again or contact HUME on WhatsApp.</p>}</div>}
    <div className="mt-12 flex items-center justify-between border-t border-black/15 pt-6">{step > 0 ? <button type="button" onClick={()=>setStep(s=>s-1)} className="inline-flex items-center gap-2 text-xs uppercase tracking-[.18em]"><ArrowLeft size={14}/> Back</button> : <span/>}{step < 3 ? <button disabled={!canContinue} type="button" onClick={()=>setStep(s=>s+1)} className="inline-flex items-center gap-2 bg-[#19231e] px-6 py-4 text-xs uppercase tracking-[.18em] text-white disabled:opacity-30">Continue <ArrowRight size={14}/></button> : <button disabled={status === "sending"} className="bg-[#19231e] px-6 py-4 text-xs uppercase tracking-[.18em] text-white disabled:opacity-50">{status === "sending" ? "Sending…" : "Request consultation"}</button>}</div>
  </form>;
}
