export type NaturalCategory = "Floral" | "Woody" | "Earthy" | "Green" | "Resinous";

export interface NaturalProduct {
  id: string;
  number: string;
  name: string;
  scientificName: string;
  origin: string;
  category: NaturalCategory;
  price: number;
  size: string;
  image: string;
  description: string;
  sensoryNotes: string;
  extractionMethod: string;
  sourcing: string;
  profile: string;
  videoUrl?: string;
}

export const NATURALS_PRODUCTS: NaturalProduct[] = [
  {
    id: "rose-otto",
    number: "Nº 01",
    name: "Rose Otto",
    scientificName: "Rosa damascena",
    origin: "KANNAUJ, UTTAR PRADESH",
    category: "Floral",
    price: 2400,
    size: "5ml",
    image: "/images/naturals/rose_otto.jpg",
    description: "Pure damask rose steam-distilled in traditional Kannauj copper stills. Voluptuous, sweet, and deeply floral.",
    sensoryNotes: "Honeyed sweetness, fresh morning dew, warm wood, green leaf.",
    extractionMethod: "Steam Distillation (Traditional Deg & Bhapka)",
    sourcing: "Sourced from multigenerational rose growers in Kannauj. Harvested before sunrise in March and April when the rosebuds are richest in essential oils.",
    profile: "Rosa damascena absolute contains citronellol, geraniol, and phenylethyl alcohol, delivering unmatched therapeutic and aromatic depth.",
  },
  {
    id: "vetiver",
    number: "Nº 02",
    name: "Vetiver",
    scientificName: "Chrysopogon zizanioides",
    origin: "MYSURU, KARNATAKA",
    category: "Earthy",
    price: 1650,
    size: "10ml",
    image: "/images/naturals/vetiver.jpg",
    description: "Damp soil, smoked wood and monsoon roots. Grounding and long-wearing on the skin.",
    sensoryNotes: "Earthy, damp soil, rich balsam, smoked wood, green root.",
    extractionMethod: "Hydro-Distillation of sun-dried roots",
    sourcing: "Sourced from organic vetiver grass plantations in Southern India. The roots are harvested at 18 months, washed, dried, and distilled slowly to lock in the deep woody undertones.",
    profile: "Contains khusimol and vetivone. Acts as a natural fixative that deepens and extends other notes on the skin.",
  },
  {
    id: "chandan",
    number: "Nº 03",
    name: "Chandan (Sandalwood)",
    scientificName: "Santalum album",
    origin: "MARAYOOR, KERALA",
    category: "Woody",
    price: 3200,
    size: "5ml",
    image: "/images/naturals/chandan.jpg",
    description: "Warm, milky, meditative. From aged East Indian sandalwood heartwood.",
    sensoryNotes: "Milky cream, warm wood, balsamic, meditative sweetness.",
    extractionMethod: "Steam distillation of heartwood powder",
    sourcing: "Sourced from the state-protected sandalwood forests of Marayoor, Kerala. Only wood from mature trees over 30 years old is harvested to ensure maximum santalol content.",
    profile: "Rich in alpha and beta santalol, providing a buttery, calming, and exceptionally long-lasting base note.",
  },
  {
    id: "bela",
    number: "Nº 04",
    name: "Bela (Champa)",
    scientificName: "Michelia champaca",
    origin: "ODISHA",
    category: "Floral",
    price: 1850,
    size: "5ml",
    image: "/images/naturals/bela.jpg",
    description: "Lush, sweet, and exotic champa blossoms hydro-distilled in traditional Kannauj degs.",
    sensoryNotes: "Sweet nectar, exotic tea, warm apricot, heady spice.",
    extractionMethod: "Traditional Deg & Bhapka Hydro-distillation",
    sourcing: "Hand-picked golden champa flowers collected from the coastal regions of Odisha. Distilled within hours of harvesting to preserve the delicate top notes.",
    profile: "Features linalool and methyl anthranilate. Uplifting, rare, and prized in classical Indian perfumery.",
  },
  {
    id: "mehndi",
    number: "Nº 05",
    name: "Mehndi (Henna)",
    scientificName: "Lawsonia inermis",
    origin: "SOJAT, RAJASTHAN",
    category: "Green",
    price: 1400,
    size: "5ml",
    image: "/images/naturals/mehndi.jpg",
    description: "Dry hay, warm resin and crushed leaf. A rare, quietly cooling attar base.",
    sensoryNotes: "Dry hay, warm balsam, crushed green leaf, herbal smoke.",
    extractionMethod: "Hydro-distillation of henna leaves on a sandalwood base",
    sourcing: "Harvested from the arid farms of Sojat, Rajasthan, where the henna leaves develop a high concentration of aromatic lawsone molecule.",
    profile: "Deeply calming, grounding, and cooling. Functions as an excellent base for traditional Indian attars.",
  },
  {
    id: "mogra",
    number: "Nº 06",
    name: "Mogra",
    scientificName: "Jasminum sambac",
    origin: "MADURAI, TAMIL NADU",
    category: "Floral",
    price: 2100,
    size: "3ml",
    image: "/images/naturals/mogra.jpg",
    description: "Night-blooming, indolic, lush. Harvested before sunrise for maximum aromatic yield.",
    sensoryNotes: "Lush white floral, clean jasmine, indolic warmth, honeyed nectar.",
    extractionMethod: "Solvent extraction of fresh mogra buds",
    sourcing: "Harvested from the jasmine fields of Madurai. The mogra buds are plucked at midnight when they open, releasing their peak volatile compounds.",
    profile: "Rich in benzyl acetate and linalool, providing a vibrant, intense, and intoxicating white floral signature.",
  },
  {
    id: "jasmine-grandiflorum",
    number: "Nº 07",
    name: "Jasmine Grandiflorum",
    scientificName: "Jasminum grandiflorum",
    origin: "COIMBATORE, TAMIL NADU",
    category: "Floral",
    price: 2400,
    size: "3ml",
    image: "/images/naturals/jasmine_grandiflorum.jpg",
    description: "Intensely floral, sweet, and rich absolute of night-blooming jasmine flowers.",
    sensoryNotes: "Sweet jasmin, exotic green tea, fruity undertone, indole.",
    extractionMethod: "Absolute extraction of night-blooming jasmine",
    sourcing: "Harvested in Coimbatore, Tamil Nadu. Hand-gathered in the early morning hours and processed immediately to retain the delicate, fruity-floral molecules.",
    profile: "Contains benzyl benzoate and phytol. Highly complex, radiant, and voluptuous scent profile.",
  },
  {
    id: "kewra",
    number: "Nº 08",
    name: "Kewra",
    scientificName: "Pandanus odorifer",
    origin: "GANJAM, ODISHA",
    category: "Green",
    price: 1200,
    size: "10ml",
    image: "/images/naturals/kewra.jpg",
    description: "Rose-like with a resinous edge. A cherished note in North Indian perfumery.",
    sensoryNotes: "Sweet honey, rosewater, green grass, resinous background.",
    extractionMethod: "Hydro-distillation of male pandanus flowers",
    sourcing: "Harvested in the Ganjam district of coastal Odisha, globally renowned for growing the finest Kewra flowers. Only the male blossoms are gathered.",
    profile: "Rich in phenylethyl methyl ether, giving it a sweet, honey-like, and highly diffusive character.",
  },
  {
    id: "khus",
    number: "Nº 09",
    name: "Khus",
    scientificName: "Vetiveria zizanioides",
    origin: "BHARATPUR, RAJASTHAN",
    category: "Earthy",
    price: 1750,
    size: "10ml",
    image: "/images/naturals/khus.jpg",
    description: "A cooler, greener cousin of Vetiver. Wet grass, river stones, monsoon air.",
    sensoryNotes: "Cool wet grass, river stones, crisp monsoon air, dark earth.",
    extractionMethod: "Hydro-distillation in traditional copper degs",
    sourcing: "Wild-harvested roots of khus grass from the marshlands of Bharatpur, Rajasthan. Distilled locally in traditional copper degs.",
    profile: "Contains high amounts of vetivenol, rendering a cool, balsamic, and refreshing wet-earth aroma.",
  },
];
