import { FLORA_GUIDES, FLORA_PRODUCT_ID, FLORA_REFERENCE } from "./flora-guides";
export { FLORA_GUIDES } from "./flora-guides";
import { SPICE_INFERNO_GUIDES, SPICE_INFERNO_PRODUCT_ID, SPICE_INFERNO_REFERENCE } from "./spice-inferno-guides";
export { SPICE_INFERNO_GUIDES } from "./spice-inferno-guides";
import { SAUVAGE_ELIXIR_GUIDES, SAUVAGE_ELIXIR_PRODUCT_ID, SAUVAGE_ELIXIR_REFERENCE } from "./sauvage-elixir-guides";
export { SAUVAGE_ELIXIR_GUIDES } from "./sauvage-elixir-guides";
import { ROMA_INTENSE_GUIDES, ROMA_INTENSE_PRODUCT_ID, ROMA_INTENSE_REFERENCE } from "./roma-intense-guides";
export { ROMA_INTENSE_GUIDES } from "./roma-intense-guides";
import { PARADOXE_GUIDES, PARADOXE_PRODUCT_ID, PARADOXE_REFERENCE } from "./paradoxe-guides";
export { PARADOXE_GUIDES } from "./paradoxe-guides";
import { OUD_MARACUJA_GUIDES, OUD_MARACUJA_PRODUCT_ID, OUD_MARACUJA_REFERENCE } from "./oud-maracuja-guides";
export { OUD_MARACUJA_GUIDES } from "./oud-maracuja-guides";
import { MYSELF_GUIDES, MYSELF_PRODUCT_ID, MYSELF_REFERENCE } from "./myself-guides";
export { MYSELF_GUIDES } from "./myself-guides";
import { LIBRE_INTENSE_GUIDES, LIBRE_INTENSE_PRODUCT_ID, LIBRE_INTENSE_REFERENCE } from "./libre-intense-guides";
export { LIBRE_INTENSE_GUIDES } from "./libre-intense-guides";
import { JAZZ_CLUB_GUIDES, JAZZ_CLUB_PRODUCT_ID, JAZZ_CLUB_REFERENCE } from "./jazz-club-guides";
export { JAZZ_CLUB_GUIDES } from "./jazz-club-guides";
import { HOMME_INTENSE_GUIDES, HOMME_INTENSE_PRODUCT_ID, HOMME_INTENSE_REFERENCE } from "./homme-intense-guides";
export { HOMME_INTENSE_GUIDES } from "./homme-intense-guides";
import { HAWAS_ICE_GUIDES, HAWAS_ICE_PRODUCT_ID, HAWAS_ICE_REFERENCE } from "./hawas-ice-guides";
export { HAWAS_ICE_GUIDES } from "./hawas-ice-guides";
import { GUILTY_POUR_HOMME_GUIDES, GUILTY_POUR_HOMME_PRODUCT_ID, GUILTY_POUR_HOMME_REFERENCE } from "./guilty-pour-homme-guides";
export { GUILTY_POUR_HOMME_GUIDES } from "./guilty-pour-homme-guides";
import { BR_540_GUIDES, BR_540_PRODUCT_ID, BR_540_REFERENCE } from "./br-540-guides";
export { BR_540_GUIDES } from "./br-540-guides";
import { ALLURE_SPORT_GUIDES, ALLURE_SPORT_PRODUCT_ID, ALLURE_SPORT_REFERENCE } from "./allure-sport-guides";
export { ALLURE_SPORT_GUIDES } from "./allure-sport-guides";
import { TOBACCO_VANILLE_GUIDES, TOBACCO_VANILLE_PRODUCT_ID, TOBACCO_VANILLE_REFERENCE } from "./tobacco-vanille-guides";
export { TOBACCO_VANILLE_GUIDES } from "./tobacco-vanille-guides";
import { PACIFIC_CHILL_GUIDES, PACIFIC_CHILL_PRODUCT_ID, PACIFIC_CHILL_REFERENCE } from "./pacific-chill-guides";
export { PACIFIC_CHILL_GUIDES } from "./pacific-chill-guides";
import { NOIR_EXTREME_GUIDES, NOIR_EXTREME_PRODUCT_ID, NOIR_EXTREME_REFERENCE } from "./noir-extreme-guides";
export { NOIR_EXTREME_GUIDES } from "./noir-extreme-guides";
import { NIGHT_OUT_GUIDES, NIGHT_OUT_PRODUCT_ID, NIGHT_OUT_REFERENCE } from "./night-out-guides";
export { NIGHT_OUT_GUIDES } from "./night-out-guides";
import { MOST_WANTED_GUIDES, MOST_WANTED_PRODUCT_ID, MOST_WANTED_REFERENCE } from "./most-wanted-guides";
export { MOST_WANTED_GUIDES } from "./most-wanted-guides";
import { LA_NUIT_GUIDES, LA_NUIT_PRODUCT_ID, LA_NUIT_REFERENCE } from "./la-nuit-guides";
export { LA_NUIT_GUIDES } from "./la-nuit-guides";
import { JADORE_GUIDES, JADORE_PRODUCT_ID, JADORE_REFERENCE } from "./jadore-guides";
export { JADORE_GUIDES } from "./jadore-guides";
import { INVICTUS_GUIDES, INVICTUS_PRODUCT_ID, INVICTUS_REFERENCE } from "./invictus-guides";
export { INVICTUS_GUIDES } from "./invictus-guides";
import { HUGO_BOSS_MAN_GUIDES, HUGO_BOSS_MAN_PRODUCT_ID, HUGO_BOSS_MAN_REFERENCE } from "./hugo-boss-man-guides";
export { HUGO_BOSS_MAN_GUIDES } from "./hugo-boss-man-guides";
import { HER_GUIDES, HER_PRODUCT_ID, HER_REFERENCE } from "./her-guides";
export { HER_GUIDES } from "./her-guides";
import { GODDESS_GUIDES, GODDESS_PRODUCT_ID, GODDESS_REFERENCE } from "./goddess-guides";
export { GODDESS_GUIDES } from "./goddess-guides";
import { EROS_GUIDES, EROS_PRODUCT_ID, EROS_REFERENCE } from "./eros-guides";
export { EROS_GUIDES } from "./eros-guides";
import { BRIGHT_CRYSTAL_GUIDES, BRIGHT_CRYSTAL_PRODUCT_ID, BRIGHT_CRYSTAL_REFERENCE } from "./bright-crystal-guides";
export { BRIGHT_CRYSTAL_GUIDES } from "./bright-crystal-guides";
import { ANGELS_SHARE_GUIDES, ANGELS_SHARE_PRODUCT_ID, ANGELS_SHARE_REFERENCE } from "./angels-share-guides";
export { ANGELS_SHARE_GUIDES } from "./angels-share-guides";
import { ALTHAIR_GUIDES, ALTHAIR_PRODUCT_ID, ALTHAIR_REFERENCE } from "./althair-guides";
export { ALTHAIR_GUIDES } from "./althair-guides";
import { ONE_MILLION_GUIDES, ONE_MILLION_PRODUCT_ID, ONE_MILLION_REFERENCE } from "./one-million-guides";
export { ONE_MILLION_GUIDES } from "./one-million-guides";
import { Y_EDP_GUIDES, Y_EDP_PRODUCT_ID, Y_EDP_REFERENCE } from "./y-edp-guides";
export { Y_EDP_GUIDES } from "./y-edp-guides";
import { VIKING_SPIRIT_GUIDES, VIKING_SPIRIT_PRODUCT_ID, VIKING_SPIRIT_REFERENCE } from "./viking-spirit-guides";
export { VIKING_SPIRIT_GUIDES } from "./viking-spirit-guides";
import { THE_BLUE_GUIDES, THE_BLUE_PRODUCT_ID, THE_BLUE_REFERENCE } from "./the-blue-guides";
export { THE_BLUE_GUIDES } from "./the-blue-guides";
import { TERRE_DE_HERMES_GUIDES, TERRE_DE_HERMES_PRODUCT_ID, TERRE_DE_HERMES_REFERENCE } from "./terre-de-hermes-guides";
export { TERRE_DE_HERMES_GUIDES } from "./terre-de-hermes-guides";
import { SRK_SPECIAL_GUIDES, SRK_SPECIAL_PRODUCT_ID, SRK_SPECIAL_REFERENCE } from "./srk-special-guides";
export { SRK_SPECIAL_GUIDES } from "./srk-special-guides";
import { SAUVAGE_GUIDES, SAUVAGE_PRODUCT_ID, SAUVAGE_REFERENCE } from "./sauvage-guides";
export { SAUVAGE_GUIDES } from "./sauvage-guides";
import { RED_TOBACCO_GUIDES, RED_TOBACCO_PRODUCT_ID, RED_TOBACCO_REFERENCE } from "./red-tobacco-guides";
export { RED_TOBACCO_GUIDES } from "./red-tobacco-guides";
import { OUD_WOOD_GUIDES, OUD_WOOD_PRODUCT_ID, OUD_WOOD_REFERENCE } from "./oud-wood-guides";
export { OUD_WOOD_GUIDES } from "./oud-wood-guides";
import { OMBRE_NOMADE_GUIDES, OMBRE_NOMADE_PRODUCT_ID, OMBRE_NOMADE_REFERENCE } from "./ombre-nomade-guides";
export { OMBRE_NOMADE_GUIDES } from "./ombre-nomade-guides";
import { OMB_LEATHER_GUIDES, OMB_LEATHER_PRODUCT_ID, OMB_LEATHER_REFERENCE } from "./omb-leather-guides";
export { OMB_LEATHER_GUIDES } from "./omb-leather-guides";
import { AVENTUS_GUIDES, AVENTUS_PRODUCT_ID, AVENTUS_REFERENCE } from "./aventus-guides";
import { BLACK_OPIUM_GUIDES, BLACK_OPIUM_PRODUCT_ID, BLACK_OPIUM_REFERENCE } from "./black-opium-guides";
import { GOOD_GIRL_GUIDES, GOOD_GIRL_PRODUCT_ID, GOOD_GIRL_REFERENCE } from "./good-girl-guides";
import { HAWAS_GUIDES, HAWAS_PRODUCT_ID, HAWAS_REFERENCE } from "./hawas-guides";
import { IMAGINE_GUIDES, IMAGINE_PRODUCT_ID, IMAGINE_REFERENCE } from "./imagine-guides";
import { KHAMRAH_QAHWA_GUIDES, KHAMRAH_QAHWA_PRODUCT_ID, KHAMRAH_QAHWA_REFERENCE } from "./khamrah-qahwa-guides";
import { LE_MALE_ELIXIR_GUIDES, LE_MALE_ELIXIR_PRODUCT_ID, LE_MALE_ELIXIR_REFERENCE } from "./le-male-elixir-guides";
import { MYRRH_TONKA_GUIDES, MYRRH_TONKA_PRODUCT_ID, MYRRH_TONKA_REFERENCE } from "./myrrh-tonka-guides";
import { NO_5_GUIDES, NO_5_PRODUCT_ID, NO_5_REFERENCE } from "./no-5-guides";
export { NO_5_GUIDES } from "./no-5-guides";
export { MYRRH_TONKA_GUIDES } from "./myrrh-tonka-guides";
export { LE_MALE_ELIXIR_GUIDES } from "./le-male-elixir-guides";
export { KHAMRAH_QAHWA_GUIDES } from "./khamrah-qahwa-guides";
export { IMAGINE_GUIDES } from "./imagine-guides";
export { HAWAS_GUIDES } from "./hawas-guides";
export { GOOD_GIRL_GUIDES } from "./good-girl-guides";
export { BLACK_OPIUM_GUIDES } from "./black-opium-guides";
export { AVENTUS_GUIDES } from "./aventus-guides";
export const STRONG_WITH_YOU_PRODUCT_ID = "stronger-with-you-intensely";
export const STRONG_WITH_YOU_REFERENCE = "https://www.giorgioarmanibeauty-usa.com/fragrances/emporio-armani-stronger-with-you-intensely-eau-de-parfum/ww-00180-arm.html";
export const CLUSTER_UPDATED = "2026-10-02";
export interface PerfumeGuide { slug: string; title: string; answer: string; cluster?: "acqua-di-gio" | "aventus" | "black-opium" | "good-girl" | "hawas" | "imagine" | "khamrah-qahwa" | "le-male-elixir" | "myrrh-tonka" | "no-5" | "omb-leather" | "ombre-nomade" | "oud-wood" | "red-tobacco" | "sauvage" | "srk-special" | "terre-de-hermes" | "the-blue" | "viking-spirit" | "y-edp" | "1-million" | "althair" | "angels-share" | "bright-crystal" | "eros" | "goddess" | "her" | "hugo-boss-man" | "invictus" | "jadore" | "la-nuit" | "most-wanted" | "night-out" | "noir-extreme" | "pacific-chill" | "tobacco-vanille" | "allure-sport" | "br-540" | "guilty-pour-homme" | "hawas-ice" | "homme-intense" | "jazz-club" | "libre-intense" | "myself" | "oud-maracuja" | "paradoxe" | "roma-intense" | "sauvage-elixir" | "spice-inferno" | "flora"; sections: { question: string; answer: string }[]; }
const entries: [string, string, string, string, string, string, string][] = [
  ["stronger-with-you-intensely-alternatives-india", "Stronger With You Intensely Alternatives in India: What to Compare", "HUME Strong With You is an Indian inspired alternative for shoppers who enjoy the warm, sweet style of Emporio Armani Stronger With You Intensely. Compare it with nearby scent directions rather than assuming every vanilla fragrance is a substitute.", "Which alternatives belong on your shortlist?", "Start with HUME Strong With You for the intended inspiration. HUME Althair explores vanilla, spice and woods; HUME Most Wanted references a ginger, woody vanilla direction. Neither is the same inspiration, so sample them as contrasting options.", "How should you compare the options?", "Compare sweetness, opening spice and dry-down on separate days. Check stock before ordering: a listed alternative may be out of stock. Consider both the scent you prefer and the cost of a bottle you will actually use."],
  ["hume-strong-with-you-day-vs-night", "HUME Strong With You: Day vs Night Wear", "The warm, sweet inspiration direction makes HUME Strong With You a candidate for cooler evenings. Daytime suitability depends on temperature, ventilation and your application; a high oil percentage alone does not establish day-versus-night performance.", "When could daytime wear work?", "Try a small application on a cool day or in a ventilated setting. Heat can change how noticeable a fragrance feels, so judge it in the setting where you intend to wear it rather than only in an air-conditioned shop.", "How should you compare day and night?", "Use the same number of sprays on two days and record temperature, time and how it smells after an hour. This checks comfort and development; it is not a published longevity result for HUME."],
  ["hume-strong-with-you-college-office-parties", "HUME Strong With You for College, Office or Parties?", "HUME Strong With You may appeal to people who want a sweet, warm scent for social occasions. For classrooms or offices, consider personal space and fragrance policies before using a richer scent.", "How should you apply it in shared spaces?", "Begin with one spray for a personal trial and assess it before adding more. A classroom, commute and meeting room put people close together. Respect fragrance-free policies and avoid refreshing at your desk.", "What changes for parties and weddings?", "Venue size and heat matter more than the event label. An outdoor evening and a crowded indoor club require different judgement. Increase application only after you know how your bottle behaves; more sprays do not automatically improve the experience."],
  ["hume-strong-with-you-who-should-wear-it", "HUME Strong With You for Men: Who Might Enjoy It?", "HUME Strong With You is aimed at shoppers who enjoy a warm, sweet, vanilla-led inspiration rather than a crisp aquatic style. Scent preference is more useful than an age bracket or personality stereotype.", "Which preferences make it worth sampling?", "Consider it if you like sweetness balanced with warm spice and woods. If you prefer dry citrus, restrained florals or very light freshness, compare a fresher HUME option before choosing a bottle.", "Does gender determine who can wear it?", "The catalog places it in the men's range, but anyone who enjoys the scent direction can try it. Choose by comfort and preference. Gifting works better when you know the recipient already enjoys richer sweet fragrances."],
  ["stronger-with-you-intensely-dupe-india", "Choosing a Stronger With You Intensely Dupe in India", "If you are searching for a Stronger With You Intensely dupe in India, HUME Strong With You is an inspired option to evaluate. Dupe is a shopping term here, not a claim that HUME is identical to Armani or the best choice for everyone.", "What should a dupe claim actually establish?", "An inspiration name describes the intended direction. It does not prove a similarity percentage, identical ingredients or equal wear time. Ask for a sample and judge the opening and dry-down yourself.", "How can you avoid a disappointing blind buy?", "Check the exact original edition, bottle size, final checkout total and stock status. Use the comparison guide to separate known specifications from claims that still need a controlled side-by-side test."],
  ["stronger-with-you-intensely-alternative-india", "Is HUME a Stronger With You Intensely Alternative in India?", "HUME Strong With You is developed as an accessible interpretation of Emporio Armani Stronger With You Intensely's scent direction. An alternative can be useful even when it is not an exact substitute: budget, scent preference and buying confidence all matter.", "What makes an alternative worth considering?", "Look at the inspiration, current bottle price, size and sampling options together. HUME reports approximately 40% fragrance oil for this perfume; that specification does not demonstrate longer wear than the designer fragrance.", "When might you prefer the original?", "Choose the original when its specific composition, designer presentation or verified experience is essential to you. Choose an inspired option when its own scent and price fit your needs. HUME is independent of Armani."],
  ["affordable-armani-stronger-with-you-intensely-alternative", "Affordable Alternative to Armani Stronger With You Intensely: Value Guide", "HUME Strong With You offers an accessible price point for exploring the Stronger With You Intensely inspiration. A fair value comparison uses current prices and equal bottle volumes, not assumed designer prices or invented savings.", "How do you calculate value fairly?", "Divide the current bottle price by its volume to compare price per millilitre. Include delivery and any applicable discounts in the final comparison. Compare the original's current authorised-retailer price on the day you shop.", "Is the cheapest bottle always better value?", "A bottle you dislike is poor value even if it costs less. Sampling reduces that risk. Include packaging, seller reliability, return conditions and your own wear experience in the decision, rather than treating concentration as a quality score."],
  ["stronger-with-you-intensely-inspired-perfume-under-1000", "Stronger With You Intensely Inspired Perfume Under ₹1,000", "HUME Strong With You is a budget candidate for shoppers seeking the Stronger With You Intensely inspiration below ₹1,000. Use the live specification table on this page to check the current bottle price and size before ordering.", "What does the budget cover?", "The bottle listing and the checkout total are different measures. Check delivery charges and stock before buying. The ₹1,000 search budget is not a promise that every delivery destination has the same final total.", "Can you sample before committing?", "The Discovery Set is a separate purchase with its own price and sample eligibility. Visit the builder to see whether Strong With You can currently be selected; do not assume every public product is available as a sample."],
  ["how-is-hume-strong-with-you", "How Is HUME Strong With You? A Beginner's Guide", "HUME Strong With You is an inspired perfume for people exploring Armani Stronger With You Intensely's warm, sweet direction. It is designed to approach that scent profile, with approximately 40% fragrance oil reported by HUME.", "What should a first-time buyer understand?", "Inspired means an independent HUME fragrance, not an Armani bottle. The original reference helps describe the intended style. Your experience of HUME's sweetness, development and strength should come from trying the actual product.", "Where should you start?", "Read the notes guide, check the live product details and compare a sample with a scent you already know. The review guide provides a decision framework; it does not pretend to be an independent customer's wear test."],
  ["hume-strong-with-you-review", "HUME Strong With You Review: A Brand Buying Guide", "This is HUME's own buying guide to Strong With You, not an independent hands-on review. It covers the intended inspiration, stated concentration and buying considerations; controlled HUME wear-test results are not published in this guide.", "What are the reasons to consider it?", "Its intended warm, sweet inspiration and accessible bottle price are the main reasons to sample it. HUME reports approximately 40% fragrance oil and developed the fragrance with the goal of closely approaching the original scent profile.", "What should you evaluate before buying?", "Assess the opening, sweetness after an hour and final dry-down on your skin. Confirm whether it feels comfortable in your usual weather and setting. Without a documented wear test, this guide does not assign a score or promise a number of hours."],
  ["hume-strong-with-you-vs-armani-stronger-with-you-intensely", "HUME Strong With You vs Armani Stronger With You Intensely", "HUME Strong With You is an independently made inspired interpretation; Emporio Armani Stronger With You Intensely is the designer original. Compare verified specifications and current prices, while treating scent closeness and relative performance as questions for side-by-side testing.", "What can we compare confidently?", "HUME's live bottle price and size are shown below. HUME reports approximately 40% fragrance oil. Armani markets the inspiration as an Eau de Parfum; that label does not establish a precise oil percentage for a numerical concentration comparison.", "How should you compare the actual scents?", "Use one fragrance on each arm with comparable application, then swap arms on another day. Record the opening, one-hour character and dry-down. Different atomisers dispense different amounts, so spray counts alone are not a laboratory-equivalent dose."],
  ["how-close-hume-strong-with-you-to-intensely", "How Close Is HUME Strong With You to Stronger With You Intensely?", "HUME developed Strong With You with the goal of approaching the original-style scent profile closely. An intention is not a measured similarity result: this guide does not give a percentage or claim that the fragrances are indistinguishable.", "Which parts should you compare?", "Compare opening spice, aromatic character, sweetness and the vanilla-amber dry-down separately. A familiar opening does not prove the whole wear is the same. Test the exact original edition alongside the HUME bottle.", "How can you make the comparison more useful?", "Try each without knowing which is on which arm if someone can help. Write down observations before checking labels. Repeat in your usual conditions and decide whether the differences matter to you rather than chasing an unsupported similarity score."],
  ["hume-strong-with-you-longevity", "HUME Strong With You Longevity: How Long Does It Last?", "This guide does not have a documented HUME Strong With You wear test from which to give a reliable hour range. Approximately 40% fragrance oil is HUME's stated specification, not proof of a particular duration on skin or clothing.", "Which factors change longevity?", "Application amount, skin condition, weather, airflow and fabric can change perception and persistence. Becoming accustomed to a smell can also make self-assessment difficult. Ask another person at agreed intervals without prompting them with an expected result.", "How should you record a personal test?", "Record sprays, application time and conditions, then check at one, three and six hours. Distinguish detectable close to skin from noticeable at conversational distance. A single personal test should not become a universal promise."],
  ["hume-strong-with-you-projection-sillage", "HUME Strong With You Projection and Sillage Explained", "Projection is how noticeable a fragrance is around the wearer; sillage is the trail it leaves while moving. Neither is established by oil concentration alone, and this guide does not claim measured projection distances for HUME Strong With You.", "How can you assess projection?", "Ask someone at ordinary conversational distance whether they notice it after application and later in the wear. Keep room size and airflow similar. Avoid assuming that a scent you can no longer smell has disappeared for everyone else.", "How should application change by setting?", "Begin conservatively in shared spaces and increase only after trying the actual perfume. For a personal first trial, one spray is a starting point rather than a validated optimum. Do not promise a larger scent trail simply by adding more."],
  ["hume-strong-with-you-notes-explained", "HUME Strong With You Fragrance Notes Explained", "Strong With You's inspiration is a warm, sweet fragrance direction associated with spice, aromatic notes, vanilla and amber woods. Notes describe smells and accords; they are not automatically an ingredient list for HUME's formula.", "What does Armani's reference describe?", "Armani's current reference highlights pink pepper, lavender and vanilla, with chestnut and amber-wood aspects. Use that as a description of the inspiration, not evidence that the HUME formula contains the same materials or follows an identical progression.", "How do you recognise the opening and dry-down?", "Smell soon after application, then return after an hour and later in the wear. Describe whether spice, sweetness or woods dominate. The original may change across editions or batches; a note list is less decisive than a test of the bottles being compared."],
];
export const STRONG_WITH_YOU_GUIDES: PerfumeGuide[] = entries.map(([slug,title,answer,q1,a1,q2,a2]) => ({slug,title,answer,sections:[{question:q1,answer:a1},{question:q2,answer:a2}]}));
export const ACQUA_DI_GIO_PRODUCT_ID = "acqua-di-gio-profondo";
export const ACQUA_DI_GIO_REFERENCE = "https://www.giorgioarmanibeauty-usa.com/fragrances/mens-cologne/acqua-di-gio/acqua-di-gio-profondo-eau-de-parfum/A2267.html";
const acquaEntries: [string, string, string, string, string, string, string][] = [
  ["acqua-di-gio-profondo-alternatives-india", "Acqua di Giò Profondo Alternatives in India: What to Compare", "HUME Acqua di Gio is an Indian inspired alternative designed around Giorgio Armani Acqua di Giò Profondo's fresh marine direction. HUME states approximately 40% fragrance oil and focuses on accessible pricing and everyday wear. Compare aquatic and citrus options by scent preference rather than assuming every fresh perfume smells like Profondo.", "Which fresh alternatives should you compare?", "Start with HUME Acqua di Gio for the Profondo inspiration. HUME Hawas offers another aquatic direction, while HUME Imagine explores the Louis Vuitton Imagination inspiration and HUME Pacific Chill offers a different citrus-fruity direction. These are contrasting fresh choices, not identical substitutes; check each product's stock before ordering.", "How do you choose between marine and citrus freshness?", "Marine accords suggest airy, water-like freshness; citrus gives a brighter peel-like impression. Try the perfumes on separate days and compare the opening, aromatic heart and later dry-down. Pick the style you enjoy during your commute and daily routine, rather than choosing solely by concentration."],
  ["hume-acqua-di-gio-day-vs-night", "HUME Acqua di Gio: Day vs Night Wear", "HUME Acqua di Gio's intended fresh, aquatic character makes it a useful daytime option to explore for warm Indian weather. It can also suit casual evenings and dates when you prefer freshness over a heavy sweet scent. Time of day alone does not establish how long it lasts or how far it projects.", "Is it suitable for summer afternoons?", "A marine-style perfume can feel refreshing during daytime use, but heat, humidity and outdoor activity change the wearing experience. Begin with a small application and judge it during your actual commute. Approximately 40% fragrance oil is HUME's specification, not a guarantee of all-day freshness.", "Can you wear it on a night out?", "Yes, a fresh direction can fit an evening meal, casual date or outdoor gathering. Decide whether you want a clean aquatic impression or a richer sweet evening scent. Test your bottle before increasing application for a larger venue; there is no measured night-time performance result in this guide."],
  ["hume-acqua-di-gio-college-office-parties", "HUME Acqua di Gio for College, Office or Parties?", "HUME Acqua di Gio is positioned as a fresh everyday fragrance for college, office and casual outings. Its Profondo-inspired marine direction can also appeal for dates, parties and weddings when you prefer a cleaner scent style. Adjust application to personal space and venue conditions rather than following a fixed spray count for every occasion.", "How many sprays should you start with at college or work?", "For a first personal trial, start with one spray and assess it before adding more. This is a conservative starting point, not a tested optimum. Respect fragrance-free policies and avoid refreshing at a desk or in a crowded classroom. For gym visits, consider close contact and apply after exercise rather than treating perfume as a replacement for washing.", "What changes for parties, dates and weddings?", "A close dinner date needs different judgement from an airy outdoor wedding. Try the perfume ahead of the event, assess how noticeable it is and increase application only when you know your bottle. A larger spray count does not establish better longevity or guarantee compliments."],
  ["hume-acqua-di-gio-who-should-wear-it", "HUME Acqua di Gio for Men: Who Should Wear It?", "HUME Acqua di Gio may appeal to people who enjoy fresh, clean, aquatic and aromatic perfumes rather than very sweet or heavy scents. It is listed in HUME's men's range, but scent preference matters more than age or gender. Consider it for an everyday fragrance wardrobe built around marine freshness.", "Which preferences make it a good candidate to sample?", "Try it if you want an airy marine direction with an aromatic impression for work, college or casual wear. If your favourite perfumes centre on dense vanilla, tobacco or rich amber, compare those styles before choosing. A fresh perfume can complement a richer evening fragrance without replacing it.", "Is there an ideal age or personality for it?", "There is no evidence-based age bracket or personality requirement. Students, professionals and older wearers can all enjoy an aquatic scent. For gifting, look at the recipient's existing preferences and usual settings rather than assuming that every man wants the same fragrance."],
  ["acqua-di-gio-profondo-dupe-india", "Choosing an Acqua di Giò Profondo Dupe in India", "HUME Acqua di Gio is an inspired option for Indian shoppers searching for an Acqua di Giò Profondo dupe. It is developed to approach the fresh aquatic profile, with approximately 40% fragrance oil specified by HUME. Choosing the best option for you requires a scent trial; this guide does not claim an independently proven market winner.", "What does dupe mean here?", "Dupe is a common shopping term for an affordable perfume in a familiar scent direction. HUME is its own inspired fragrance, not an Armani product. The inspiration name does not prove identical ingredients, a similarity percentage or the same wear time.", "What should you check before buying in India?", "Check the exact Profondo edition you intend to compare, HUME's live price and size, stock, delivery cost and sampling eligibility. Evaluate the marine opening and later aromatic character on your own skin. Value comes from enjoying the actual fragrance as well as its price."],
  ["acqua-di-gio-profondo-alternative-india", "Is HUME an Acqua di Giò Profondo Alternative in India?", "HUME Acqua di Gio is an accessible Indian alternative for exploring the Profondo-style aquatic direction. HUME developed it with the goal of closely recreating that overall profile and reports approximately 40% fragrance oil. Scent preference, current bottle price and your wear experience should guide the choice.", "Why consider HUME instead of a designer bottle?", "Consider HUME when an inspired marine fragrance and its current price fit your everyday budget. The product card below shows the available bottle size and price dynamically. HUME's performance-focused formulation is a development goal, not evidence that it outperforms Armani.", "When might you prefer Armani's original?", "The original is the appropriate choice when its specific composition, designer presentation or your experience of that exact fragrance is essential. HUME offers an independent interpretation for a different buying decision. Compare samples where possible and choose the actual scent you prefer."],
  ["affordable-armani-acqua-di-gio-profondo-alternative", "Affordable Alternative to Armani Acqua di Giò Profondo: Value Guide", "HUME Acqua di Gio offers an accessible way to explore a fresh marine inspiration without committing to a designer bottle. Its current price and size are shown from HUME's catalog below. A fair saving comparison requires the original's current authorised-retailer price and equivalent bottle volumes, rather than an assumed discount percentage.", "How should you compare price and bottle options?", "Divide each current bottle price by its volume to compare cost per millilitre, then include delivery and any applicable offers. The HUME card shows the listed size; do not assume other sizes are available. Sampling has a separate cost and can be useful before choosing a full bottle.", "How do concentration and everyday usability affect value?", "HUME states approximately 40% fragrance oil; Armani identifies the reference as Eau de Parfum without a verified numerical oil percentage here. Concentration alone does not establish scent quality or wear time. Value also depends on whether you enjoy the aquatic direction during work, travel and casual use."],
  ["acqua-di-gio-profondo-inspired-perfume-under-1000", "Acqua di Giò Profondo Inspired Perfume Under ₹1,000", "HUME Acqua di Gio is an option to check when searching for a Profondo-inspired aquatic perfume under ₹1,000 in India. Use the live product card below to confirm its current bottle price, size and availability. This is an independently made HUME perfume, not an Armani bottle at a reduced price.", "Does the ₹1,000 budget include delivery?", "The listed bottle price and the final checkout total may differ. Check delivery charges and applicable offers before ordering. If the live price moves above your budget, use that current value rather than relying on the article title as a fixed-price promise.", "Can you try a sample first?", "Explore the Discovery Set builder to check current Acqua di Gio eligibility and the set's own price. A sample can help you decide whether the marine direction suits your routine. Public catalog availability does not automatically mean a perfume is selectable in the set."],
  ["how-is-hume-acqua-di-gio", "How Is HUME Acqua di Gio? A Beginner's Guide", "HUME Acqua di Gio is designed around Acqua di Giò Profondo's fresh aquatic and marine style, with an aromatic character rather than dense sweetness. HUME reports approximately 40% fragrance oil and aims to closely approach the inspiration profile. It is an option to explore for daily wear and warm-weather routines, with personal testing needed to assess strength and comfort.", "What does its fresh marine direction mean?", "Marine describes an airy, water-like scent impression; aromatic describes a herbal freshness. These terms explain the intended style, not the HUME ingredient list. Compare the actual opening and dry-down on your skin before deciding whether you enjoy the balance.", "Where should a new buyer begin?", "Start with the notes guide, check the live product details and consider a sample if currently eligible. Wear it during your usual commute or workday to judge versatility and comfort. A concentration figure cannot tell you whether your own preference is aquatic, citrus or sweet."],
  ["hume-acqua-di-gio-review", "HUME Acqua di Gio Review: A Brand Buying Guide", "This is HUME's own Acqua di Gio buying guide, not an independent hands-on review. It explains the Profondo-inspired marine direction, HUME's stated approximately 40% fragrance oil and the buying questions to evaluate. Documented HUME wear-test results are not supplied here, so it gives no invented longevity score or compliment guarantee.", "How should you assess the first spray, heart and dry-down?", "At first application, note the balance of brightness and aquatic freshness. Return later to assess aromatic character and the final impression, recording your own observations rather than assuming Armani's notes are HUME's ingredients. Compare whether the progression feels comfortable indoors and during your usual weather.", "Who should consider it and what should they check?", "Fresh-scent enthusiasts seeking an accessible everyday marine option may want to sample it; people who mainly enjoy rich sweet fragrances should compare other directions. Check current price, stock and sample eligibility below. Assess projection and longevity in your actual conditions; compliments depend on others' preferences and are not promised."],
  ["hume-acqua-di-gio-vs-armani-acqua-di-gio-profondo", "HUME Acqua di Gio vs Armani Acqua di Giò Profondo", "HUME Acqua di Gio is an independent inspired alternative; Giorgio Armani Acqua di Giò Profondo Eau de Parfum is the designer reference. HUME states approximately 40% fragrance oil and aims at an accessible marine-style experience. Compare verified specifications first, then test opening, aromatic freshness and dry-down side by side rather than assuming equal performance.", "What can a factual comparison establish?", "The table below distinguishes the brands, inspiration, concentration statements and price sources. Armani's Eau de Parfum label does not provide a verified numerical oil percentage for this guide. HUME's live price is available here; obtain the designer's current local price before calculating savings.", "How should you compare scent and performance?", "Try comparable application on separate arms, then swap arms on another day. Record initial marine freshness, later aromatic character and final dry-down along with heat, humidity and activity. Different atomisers dispense different amounts; spray counts alone are not a laboratory-equivalent dose, and no similarity percentage is asserted here."],
  ["how-close-hume-acqua-di-gio-to-profondo", "How Close Is HUME Acqua di Gio to Acqua di Giò Profondo?", "HUME developed Acqua di Gio with the goal of recreating the overall Profondo-style fresh marine profile as closely as possible. That objective is not a measured similarity result. Without a documented side-by-side comparison, this guide does not invent differences or claim the perfumes are indistinguishable.", "Which parts of the scent should you compare?", "Assess the opening's brightness, aquatic feel and marine character, then the aromatic heart and later dry-down. A similar opening does not prove identical development. Compare the exact Profondo edition you mean, since Eau de Parfum and Parfum are separate references.", "How can you identify meaningful differences?", "Write down observations before checking which sample is which, with someone helping if possible. Repeat during your usual routine and note whether either feels sweeter, sharper, more herbal or more subdued to you. These are comparison prompts, not claimed differences established by HUME testing."],
  ["hume-acqua-di-gio-longevity", "HUME Acqua di Gio Longevity: How Long Does It Last?", "A documented HUME Acqua di Gio wear test is not available in this guide, so a reliable hour range cannot be stated. HUME's approximately 40% fragrance-oil concentration provides formulation context, not proof of a specific duration. Skin, application, weather and activity can all change the wearing experience.", "What affects longevity in Indian weather?", "Consider skin condition, spray amount, heat, humidity, airflow and activity together. Clothing and skin can behave differently, and fabric may mark, so follow product directions and test an inconspicuous area before applying to clothes. Store the bottle away from heat and direct sunlight according to its care instructions.", "How should you test your own bottle?", "Record application time, sprays and conditions, then check at one, three and six hours without treating those checkpoints as a predicted duration. Distinguish detectable close to skin from noticeable at conversational distance. Ask another person for an unprompted assessment to reduce the effect of becoming accustomed to the smell."],
  ["hume-acqua-di-gio-projection-sillage", "HUME Acqua di Gio Projection and Sillage Explained", "Projection describes how noticeable HUME Acqua di Gio is around you; sillage describes the trail as you move. This guide has no measured distances or projection duration for the perfume. Its approximately 40% fragrance oil does not by itself establish the size of a scent cloud or how it changes after the opening.", "How can you assess the opening and later projection?", "Ask someone at normal conversational distance whether they notice it shortly after application and later in the wear. Keep room size, airflow and application similar across trials. Indoor and outdoor results may differ, especially with heat and wind, so record the conditions instead of treating one observation as universal.", "How should you apply it for work or a party?", "Begin with one spray for a personal first trial and adjust only after assessing the actual bottle; this is not a validated ideal count. Use less when sharing close space and respect office policies. Clothing application needs care and fabric testing; it is not a guaranteed route to stronger projection."],
  ["hume-acqua-di-gio-notes-explained", "HUME Acqua di Gio Fragrance Notes Explained", "HUME Acqua di Gio aims at a fresh marine and aromatic direction inspired by Acqua di Giò Profondo. Imagine an airy aquatic opening, herbal freshness through the heart and a more grounded later impression. This describes the inspiration style rather than a verified HUME ingredient list or measured note progression.", "What does Armani's official Profondo reference describe?", "Armani's Eau de Parfum reference describes citrus and marine freshness with an aromatic heart. Those descriptions suggest brightness, an airy water-like effect and a herbal accent. They help explain the inspiration; they do not establish that the HUME formula uses the same materials or develops identically.", "How do you understand opening, heart and dry-down?", "The opening is the first impression after spraying; the heart is the character as that first burst settles; the dry-down is what remains later. Notice whether aquatic freshness, aromatic character or a softer grounded impression dominates at each stage. Scent notes describe perceived smells and accords, not automatically ingredients."],
];
export const ACQUA_DI_GIO_GUIDES: PerfumeGuide[] = acquaEntries.map(([slug,title,answer,q1,a1,q2,a2]) => ({slug,title,answer,cluster:"acqua-di-gio",sections:[{question:q1,answer:a1},{question:q2,answer:a2}]}));
export const PERFUME_GUIDES = [...STRONG_WITH_YOU_GUIDES, ...ACQUA_DI_GIO_GUIDES, ...AVENTUS_GUIDES, ...BLACK_OPIUM_GUIDES, ...GOOD_GIRL_GUIDES, ...HAWAS_GUIDES, ...IMAGINE_GUIDES, ...KHAMRAH_QAHWA_GUIDES, ...LE_MALE_ELIXIR_GUIDES, ...MYRRH_TONKA_GUIDES, ...NO_5_GUIDES, ...OMB_LEATHER_GUIDES, ...OMBRE_NOMADE_GUIDES, ...OUD_WOOD_GUIDES, ...RED_TOBACCO_GUIDES, ...SAUVAGE_GUIDES, ...SRK_SPECIAL_GUIDES, ...TERRE_DE_HERMES_GUIDES, ...THE_BLUE_GUIDES, ...VIKING_SPIRIT_GUIDES, ...Y_EDP_GUIDES, ...ONE_MILLION_GUIDES, ...ALTHAIR_GUIDES, ...ANGELS_SHARE_GUIDES, ...BRIGHT_CRYSTAL_GUIDES, ...EROS_GUIDES, ...GODDESS_GUIDES, ...HER_GUIDES, ...HUGO_BOSS_MAN_GUIDES, ...INVICTUS_GUIDES, ...JADORE_GUIDES, ...LA_NUIT_GUIDES, ...MOST_WANTED_GUIDES, ...NIGHT_OUT_GUIDES, ...NOIR_EXTREME_GUIDES, ...PACIFIC_CHILL_GUIDES, ...TOBACCO_VANILLE_GUIDES, ...ALLURE_SPORT_GUIDES, ...BR_540_GUIDES, ...GUILTY_POUR_HOMME_GUIDES, ...HAWAS_ICE_GUIDES, ...HOMME_INTENSE_GUIDES, ...JAZZ_CLUB_GUIDES, ...LIBRE_INTENSE_GUIDES, ...MYSELF_GUIDES, ...OUD_MARACUJA_GUIDES, ...PARADOXE_GUIDES, ...ROMA_INTENSE_GUIDES, ...SAUVAGE_ELIXIR_GUIDES, ...SPICE_INFERNO_GUIDES, ...FLORA_GUIDES];
export function getPerfumeGuide(slug: string) { return PERFUME_GUIDES.find(guide => guide.slug === slug); }
export function getGuideCluster(guide: PerfumeGuide) {
  if (guide.cluster === "flora") return { productId: FLORA_PRODUCT_ID, name: "HUME Flora", inspiration: "Gucci Flora", brand: "Gucci", reference: FLORA_REFERENCE, guides: FLORA_GUIDES };
  if (guide.cluster === "spice-inferno") return { productId: SPICE_INFERNO_PRODUCT_ID, name: "HUME Spice Inferno", inspiration: "Viktor & Rolf Spicebomb", brand: "Viktor & Rolf", reference: SPICE_INFERNO_REFERENCE, guides: SPICE_INFERNO_GUIDES };
  if (guide.cluster === "sauvage-elixir") return { productId: SAUVAGE_ELIXIR_PRODUCT_ID, name: "HUME Sauvage Elixir", inspiration: "Dior Sauvage Elixir", brand: "Dior", reference: SAUVAGE_ELIXIR_REFERENCE, guides: SAUVAGE_ELIXIR_GUIDES };
  if (guide.cluster === "roma-intense") return { productId: ROMA_INTENSE_PRODUCT_ID, name: "HUME Roma Intense", inspiration: "Valentino Born in Roma Intense", brand: "Valentino", reference: ROMA_INTENSE_REFERENCE, guides: ROMA_INTENSE_GUIDES };
  if (guide.cluster === "paradoxe") return { productId: PARADOXE_PRODUCT_ID, name: "HUME Paradoxe", inspiration: "Prada Paradoxe", brand: "Prada", reference: PARADOXE_REFERENCE, guides: PARADOXE_GUIDES };
  if (guide.cluster === "oud-maracuja") return { productId: OUD_MARACUJA_PRODUCT_ID, name: "HUME Oud Maracuja", inspiration: "Maison Crivelli Oud Maracuja", brand: "Maison Crivelli", reference: OUD_MARACUJA_REFERENCE, guides: OUD_MARACUJA_GUIDES };
  if (guide.cluster === "myself") return { productId: MYSELF_PRODUCT_ID, name: "HUME Myself", inspiration: "YSL MYSLF", brand: "Yves Saint Laurent", reference: MYSELF_REFERENCE, guides: MYSELF_GUIDES };
  if (guide.cluster === "libre-intense") return { productId: LIBRE_INTENSE_PRODUCT_ID, name: "HUME Libre Intense", inspiration: "YSL Libre Intense", brand: "Yves Saint Laurent", reference: LIBRE_INTENSE_REFERENCE, guides: LIBRE_INTENSE_GUIDES };
  if (guide.cluster === "jazz-club") return { productId: JAZZ_CLUB_PRODUCT_ID, name: "HUME Jazz Club", inspiration: "Maison Margiela REPLICA Jazz Club", brand: "Maison Margiela", reference: JAZZ_CLUB_REFERENCE, guides: JAZZ_CLUB_GUIDES };
  if (guide.cluster === "homme-intense") return { productId: HOMME_INTENSE_PRODUCT_ID, name: "HUME Homme Intense", inspiration: "Dior Homme Intense", brand: "Dior", reference: HOMME_INTENSE_REFERENCE, guides: HOMME_INTENSE_GUIDES };
  if (guide.cluster === "hawas-ice") return { productId: HAWAS_ICE_PRODUCT_ID, name: "HUME Hawas Ice", inspiration: "Rasasi Hawas Ice", brand: "Rasasi", reference: HAWAS_ICE_REFERENCE, guides: HAWAS_ICE_GUIDES };
  if (guide.cluster === "guilty-pour-homme") return { productId: GUILTY_POUR_HOMME_PRODUCT_ID, name: "HUME Guilty Pour Homme", inspiration: "Gucci Guilty Pour Homme", brand: "Gucci", reference: GUILTY_POUR_HOMME_REFERENCE, guides: GUILTY_POUR_HOMME_GUIDES };
  if (guide.cluster === "br-540") return { productId: BR_540_PRODUCT_ID, name: "HUME BR 540", inspiration: "Maison Francis Kurkdjian Baccarat Rouge 540", brand: "Maison Francis Kurkdjian", reference: BR_540_REFERENCE, guides: BR_540_GUIDES };
  if (guide.cluster === "allure-sport") return { productId: ALLURE_SPORT_PRODUCT_ID, name: "HUME Allure Sport", inspiration: "Chanel Allure Homme Sport", brand: "Chanel", reference: ALLURE_SPORT_REFERENCE, guides: ALLURE_SPORT_GUIDES };
  if (guide.cluster === "tobacco-vanille") return { productId: TOBACCO_VANILLE_PRODUCT_ID, name: "HUME Tobacco Vanille", inspiration: "Tom Ford Tobacco Vanille Eau de Parfum", brand: "Tom Ford", reference: TOBACCO_VANILLE_REFERENCE, guides: TOBACCO_VANILLE_GUIDES };
  if (guide.cluster === "pacific-chill") return { productId: PACIFIC_CHILL_PRODUCT_ID, name: "HUME Pacific Chill", inspiration: "Louis Vuitton Pacific Chill", brand: "Louis Vuitton", reference: PACIFIC_CHILL_REFERENCE, guides: PACIFIC_CHILL_GUIDES };
  if (guide.cluster === "noir-extreme") return { productId: NOIR_EXTREME_PRODUCT_ID, name: "HUME Noir Extreme", inspiration: "Tom Ford Noir Extreme Eau de Parfum", brand: "Tom Ford", reference: NOIR_EXTREME_REFERENCE, guides: NOIR_EXTREME_GUIDES };
  if (guide.cluster === "night-out") return { productId: NIGHT_OUT_PRODUCT_ID, name: "HUME Night Out", inspiration: "Afnan 9 PM Night Out", brand: "Afnan", reference: NIGHT_OUT_REFERENCE, guides: NIGHT_OUT_GUIDES };
  if (guide.cluster === "most-wanted") return { productId: MOST_WANTED_PRODUCT_ID, name: "HUME Most Wanted", inspiration: "Azzaro The Most Wanted Parfum", brand: "Azzaro", reference: MOST_WANTED_REFERENCE, guides: MOST_WANTED_GUIDES };
  if (guide.cluster === "la-nuit") return { productId: LA_NUIT_PRODUCT_ID, name: "HUME La Nuit", inspiration: "YSL La Nuit de L’Homme Eau de Toilette", brand: "Yves Saint Laurent", reference: LA_NUIT_REFERENCE, guides: LA_NUIT_GUIDES };
  if (guide.cluster === "jadore") return { productId: JADORE_PRODUCT_ID, name: "HUME J’adore", inspiration: "Dior J’adore Eau de Parfum", brand: "Dior", reference: JADORE_REFERENCE, guides: JADORE_GUIDES };
  if (guide.cluster === "invictus") return { productId: INVICTUS_PRODUCT_ID, name: "HUME Invictus", inspiration: "Rabanne Invictus Eau de Toilette", brand: "Rabanne", reference: INVICTUS_REFERENCE, guides: INVICTUS_GUIDES };
  if (guide.cluster === "hugo-boss-man") return { productId: HUGO_BOSS_MAN_PRODUCT_ID, name: "HUME Hugo Boss Man", inspiration: "HUGO Man Eau de Toilette", brand: "Hugo Boss", reference: HUGO_BOSS_MAN_REFERENCE, guides: HUGO_BOSS_MAN_GUIDES };
  if (guide.cluster === "her") return { productId: HER_PRODUCT_ID, name: "HUME Her", inspiration: "Burberry Her Eau de Parfum", brand: "Burberry", reference: HER_REFERENCE, guides: HER_GUIDES };
  if (guide.cluster === "goddess") return { productId: GODDESS_PRODUCT_ID, name: "HUME Goddess", inspiration: "Burberry Goddess Eau de Parfum", brand: "Burberry", reference: GODDESS_REFERENCE, guides: GODDESS_GUIDES };
  if (guide.cluster === "eros") return { productId: EROS_PRODUCT_ID, name: "HUME Eros", inspiration: "Versace Eros Eau de Parfum", brand: "Versace", reference: EROS_REFERENCE, guides: EROS_GUIDES };
  if (guide.cluster === "bright-crystal") return { productId: BRIGHT_CRYSTAL_PRODUCT_ID, name: "HUME Bright Crystal", inspiration: "Versace Bright Crystal Eau de Toilette", brand: "Versace", reference: BRIGHT_CRYSTAL_REFERENCE, guides: BRIGHT_CRYSTAL_GUIDES };
  if (guide.cluster === "angels-share") return { productId: ANGELS_SHARE_PRODUCT_ID, name: "HUME Angels Share", inspiration: "Kilian Angels’ Share", brand: "Kilian", reference: ANGELS_SHARE_REFERENCE, guides: ANGELS_SHARE_GUIDES };
  if (guide.cluster === "althair") return { productId: ALTHAIR_PRODUCT_ID, name: "HUME Althair", inspiration: "Parfums de Marly Althaïr Eau de Parfum", brand: "Parfums de Marly", reference: ALTHAIR_REFERENCE, guides: ALTHAIR_GUIDES };
  if (guide.cluster === "1-million") return { productId: ONE_MILLION_PRODUCT_ID, name: "HUME 1 Million", inspiration: "Rabanne 1 Million Eau de Toilette", brand: "Rabanne", reference: ONE_MILLION_REFERENCE, guides: ONE_MILLION_GUIDES };
  if (guide.cluster === "y-edp") return { productId: Y_EDP_PRODUCT_ID, name: "HUME Y EDP", inspiration: "YSL Y Eau de Parfum", brand: "Yves Saint Laurent", reference: Y_EDP_REFERENCE, guides: Y_EDP_GUIDES };
  if (guide.cluster === "viking-spirit") return { productId: VIKING_SPIRIT_PRODUCT_ID, name: "HUME Viking Spirit", inspiration: "Creed Viking", brand: "Creed", reference: VIKING_SPIRIT_REFERENCE, guides: VIKING_SPIRIT_GUIDES };
  if (guide.cluster === "the-blue") return { productId: THE_BLUE_PRODUCT_ID, name: "HUME The Blue", inspiration: "Chanel Bleu de Chanel", brand: "Chanel", reference: THE_BLUE_REFERENCE, guides: THE_BLUE_GUIDES };
  if (guide.cluster === "terre-de-hermes") return { productId: TERRE_DE_HERMES_PRODUCT_ID, name: "HUME Terre de Hermes", inspiration: "Hermès Terre d’Hermès Eau de Toilette", brand: "Hermès", reference: TERRE_DE_HERMES_REFERENCE, guides: TERRE_DE_HERMES_GUIDES };
  if (guide.cluster === "srk-special") return { productId: SRK_SPECIAL_PRODUCT_ID, name: "HUME SRK Special", inspiration: "Diptyque Tam Dao + Dunhill Icon", brand: "Diptyque or Dunhill", reference: SRK_SPECIAL_REFERENCE, guides: SRK_SPECIAL_GUIDES };
  if (guide.cluster === "sauvage") return { productId: SAUVAGE_PRODUCT_ID, name: "HUME Sauvage", inspiration: "Dior Sauvage Eau de Toilette", brand: "Dior", reference: SAUVAGE_REFERENCE, guides: SAUVAGE_GUIDES };
  if (guide.cluster === "red-tobacco") return { productId: RED_TOBACCO_PRODUCT_ID, name: "HUME Red Tobacco", inspiration: "Mancera Red Tobacco", brand: "Mancera", reference: RED_TOBACCO_REFERENCE, guides: RED_TOBACCO_GUIDES };
  if (guide.cluster === "oud-wood") return { productId: OUD_WOOD_PRODUCT_ID, name: "HUME Oud Wood", inspiration: "Tom Ford Oud Wood Eau de Parfum", brand: "Tom Ford", reference: OUD_WOOD_REFERENCE, guides: OUD_WOOD_GUIDES };
  if (guide.cluster === "ombre-nomade") return { productId: OMBRE_NOMADE_PRODUCT_ID, name: "HUME Ombre Nomade", inspiration: "Louis Vuitton Ombre Nomade", brand: "Louis Vuitton", reference: OMBRE_NOMADE_REFERENCE, guides: OMBRE_NOMADE_GUIDES };
  if (guide.cluster === "omb-leather") return { productId: OMB_LEATHER_PRODUCT_ID, name: "HUME Omb Leather", inspiration: "Tom Ford Ombré Leather Eau de Parfum", brand: "Tom Ford", reference: OMB_LEATHER_REFERENCE, guides: OMB_LEATHER_GUIDES };
  if (guide.cluster === "no-5") return { productId: NO_5_PRODUCT_ID, name: "HUME No 5", inspiration: "Chanel N°5 Eau de Parfum", brand: "Chanel", reference: NO_5_REFERENCE, guides: NO_5_GUIDES };
  if (guide.cluster === "myrrh-tonka") return { productId: MYRRH_TONKA_PRODUCT_ID, name: "HUME Myrrh & Tonka", inspiration: "Jo Malone Myrrh & Tonka Cologne Intense", brand: "Jo Malone London", reference: MYRRH_TONKA_REFERENCE, guides: MYRRH_TONKA_GUIDES };
  if (guide.cluster === "le-male-elixir") return { productId: LE_MALE_ELIXIR_PRODUCT_ID, name: "HUME Le Male Elixir", inspiration: "Jean Paul Gaultier Le Male Elixir Parfum", brand: "Jean Paul Gaultier", reference: LE_MALE_ELIXIR_REFERENCE, guides: LE_MALE_ELIXIR_GUIDES };
  if (guide.cluster === "khamrah-qahwa") return { productId: KHAMRAH_QAHWA_PRODUCT_ID, name: "HUME Khamrah Qahwa", inspiration: "Lattafa Khamrah Qahwa", brand: "Lattafa", reference: KHAMRAH_QAHWA_REFERENCE, guides: KHAMRAH_QAHWA_GUIDES };
  if (guide.cluster === "imagine") return { productId: IMAGINE_PRODUCT_ID, name: "HUME Imagine", inspiration: "Louis Vuitton Imagination", brand: "Louis Vuitton", reference: IMAGINE_REFERENCE, guides: IMAGINE_GUIDES };
  if (guide.cluster === "hawas") return { productId: HAWAS_PRODUCT_ID, name: "HUME Hawas", inspiration: "Rasasi Hawas for Him", brand: "Rasasi", reference: HAWAS_REFERENCE, guides: HAWAS_GUIDES };
  if (guide.cluster === "good-girl") return { productId: GOOD_GIRL_PRODUCT_ID, name: "HUME Good Girl", inspiration: "Carolina Herrera Good Girl Eau de Parfum", brand: "Carolina Herrera", reference: GOOD_GIRL_REFERENCE, guides: GOOD_GIRL_GUIDES };
  if (guide.cluster === "black-opium") return { productId: BLACK_OPIUM_PRODUCT_ID, name: "HUME Black Opium", inspiration: "YSL Black Opium Eau de Parfum", brand: "YSL", reference: BLACK_OPIUM_REFERENCE, guides: BLACK_OPIUM_GUIDES };
  if (guide.cluster === "aventus") return { productId: AVENTUS_PRODUCT_ID, name: "HUME Aventus", inspiration: "Creed Aventus", brand: "Creed", reference: AVENTUS_REFERENCE, guides: AVENTUS_GUIDES };
  return guide.cluster === "acqua-di-gio"
    ? { productId: ACQUA_DI_GIO_PRODUCT_ID, name: "HUME Acqua di Gio", inspiration: "Giorgio Armani Acqua di Giò Profondo", brand: "Armani", reference: ACQUA_DI_GIO_REFERENCE, guides: ACQUA_DI_GIO_GUIDES }
    : { productId: STRONG_WITH_YOU_PRODUCT_ID, name: "HUME Strong With You", inspiration: "Emporio Armani Stronger With You Intensely", brand: "Armani", reference: STRONG_WITH_YOU_REFERENCE, guides: STRONG_WITH_YOU_GUIDES };
}
